FROM cgr.dev/chainguard/wolfi-base@sha256:6a8dca4c2153cfc11d559cfa6172c187b896423d833f3d48a4c1c44ab55596d7
RUN apk add --no-cache \
      bash=5.3-r12 \
      build-base=1-r9 \
      ca-certificates=20260413-r1 \
      git=2.55.0-r4 \
      glibc-2.44=2.44-r8 \
      glibc-2.44-dev=2.44-r8 \
      glibc-2.44-locale-posix=2.44-r8 \
      go-1.26=1.26.9-r0 \
      jq=1.8.2-r1 \
      ld-linux-2.44=2.44-r8 \
      libcrypt1-2.44=2.44-r8 \
      libcrypto3=3.6.5-r1 \
      libssl3=3.6.5-r1 \
      nodejs-24=24.19.0-r0 \
      npm=12.0.2-r0 \
      py3.14-pip=26.2.1-r2 \
      py3.14-pip-base=26.2.1-r2 \
      python-3.14=3.14.7_git20260925-r0 \
      rust-1.96=1.96.1-r0 \
      zlib=1.3.2-r7
RUN zlib_commit=4d03c63b8648ab83053a6f00d304a5d6f9aa1ed7 \
 && zlib_archive=/tmp/zlib-${zlib_commit}.tar.gz \
 && python3 -c 'import sys, urllib.request; urllib.request.urlretrieve(sys.argv[1], sys.argv[2])' \
      "https://codeload.github.com/madler/zlib/tar.gz/${zlib_commit}" "$zlib_archive" \
 && printf '%s  %s\n' b4d20a2c640eb3bc3fba2d41931076ff6523826defffcaf45292991520e2623a "$zlib_archive" \
      | busybox sha256sum -c - \
 && busybox tar -xzf "$zlib_archive" -C /tmp \
 && cd "/tmp/zlib-${zlib_commit}" \
 && ./configure --prefix=/usr \
 && make -j1 \
 && make test \
 && make install \
 && cc -I/usr/include test/gznonblock.c -L/usr/lib -Wl,-rpath,/usr/lib -lz -o /tmp/zlib-gznonblock \
 && /tmp/zlib-gznonblock \
 && mkdir -p /usr/share/aeontra/security \
 && printf '%s\n' "$zlib_commit" > /usr/share/aeontra/security/zlib-gzwrite-fix \
 && rm -rf "$zlib_archive" "/tmp/zlib-${zlib_commit}" /tmp/zlib-gznonblock
RUN brace_archive=/tmp/brace-expansion-5.0.11.tgz \
 && undici_archive=/tmp/undici-6.28.1.tgz \
 && ip_archive=/tmp/ip-address-10.3.1.tgz \
 && NPM_CONFIG_CACHE=/tmp/npm-cache npm pack --ignore-scripts --pack-destination /tmp brace-expansion@5.0.11 \
 && NPM_CONFIG_CACHE=/tmp/npm-cache npm pack --ignore-scripts --pack-destination /tmp undici@6.28.1 \
 && NPM_CONFIG_CACHE=/tmp/npm-cache npm pack --ignore-scripts --pack-destination /tmp ip-address@10.3.1 \
 && printf '%s  %s\n' 67bb5a1b4d4a8ff497d845a0b891ffe6b7233aea2202641315cec88d0fff15eb "$brace_archive" \
      | busybox sha256sum -c - \
 && printf '%s  %s\n' e18191aac9c0ff43dac7fe9b10b7041a22d07addb7b66a6e8ac14a52a5b69b74 "$undici_archive" \
      | busybox sha256sum -c - \
 && printf '%s  %s\n' ad1790063beea11a312c801df30d58e147de762f4f77787552376eb7424623e5 "$ip_archive" \
      | busybox sha256sum -c - \
 && mkdir -p /tmp/brace-unpack /tmp/undici-unpack /tmp/ip-unpack \
 && busybox tar -xzf "$brace_archive" -C /tmp/brace-unpack \
 && busybox tar -xzf "$undici_archive" -C /tmp/undici-unpack \
 && busybox tar -xzf "$ip_archive" -C /tmp/ip-unpack \
 && rm -rf /usr/lib/node_modules/npm/node_modules/brace-expansion \
             /usr/lib/node_modules/npm/node_modules/undici \
             /usr/lib/node_modules/npm/node_modules/ip-address \
 && mkdir -p /usr/lib/node_modules/npm/node_modules/brace-expansion \
             /usr/lib/node_modules/npm/node_modules/undici \
             /usr/lib/node_modules/npm/node_modules/ip-address \
 && cp -a /tmp/brace-unpack/package/. /usr/lib/node_modules/npm/node_modules/brace-expansion/ \
 && cp -a /tmp/undici-unpack/package/. /usr/lib/node_modules/npm/node_modules/undici/ \
 && cp -a /tmp/ip-unpack/package/. /usr/lib/node_modules/npm/node_modules/ip-address/ \
 && test "$(node -p "require('/usr/lib/node_modules/npm/node_modules/brace-expansion/package.json').version")" = 5.0.11 \
 && test "$(node -p "require('/usr/lib/node_modules/npm/node_modules/undici/package.json').version")" = 6.28.1 \
 && test "$(find /usr/lib/node_modules/npm -path '*/brace-expansion/package.json' -type f | wc -l)" -eq 1 \
 && test "$(find /usr/lib/node_modules/npm -path '*/undici/package.json' -type f | wc -l)" -eq 1 \
 && test "$(node -p "require('/usr/lib/node_modules/npm/node_modules/ip-address/package.json').version")" = 10.3.1 \
 && rm -rf "$brace_archive" "$undici_archive" "$ip_archive" /tmp/brace-unpack /tmp/undici-unpack /tmp/ip-unpack /tmp/npm-cache
WORKDIR /workspace
CMD ["/bin/bash"]
