// Command coverage-gate enforces package-specific Go coverage thresholds against a
// coverprofile generated by `go test -coverprofile`.
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"

	"github.com/charle-z/mcp-devbox/internal/coveragegate"
)

type thresholdFlags []coveragegate.Threshold

func (f *thresholdFlags) String() string {
	parts := make([]string, 0, len(*f))
	for _, threshold := range *f {
		parts = append(parts, fmt.Sprintf("%s=%.1f", threshold.Package, threshold.Minimum))
	}
	return strings.Join(parts, ",")
}

func (f *thresholdFlags) Set(value string) error {
	threshold, err := parseThreshold(value)
	if err != nil {
		return err
	}
	*f = append(*f, threshold)
	return nil
}

func parseThreshold(value string) (coveragegate.Threshold, error) {
	separator := strings.LastIndex(value, "=")
	if separator <= 0 || separator == len(value)-1 {
		return coveragegate.Threshold{}, fmt.Errorf("threshold must be package=percent")
	}
	packagePath := strings.TrimSpace(value[:separator])
	minimum, err := strconv.ParseFloat(strings.TrimSpace(value[separator+1:]), 64)
	if err != nil || minimum < 0 || minimum > 100 {
		return coveragegate.Threshold{}, fmt.Errorf("threshold percentage must be between 0 and 100")
	}
	if packagePath == "" {
		return coveragegate.Threshold{}, fmt.Errorf("threshold package is required")
	}
	return coveragegate.Threshold{Package: packagePath, Minimum: minimum}, nil
}

func run(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("coverage-gate", flag.ContinueOnError)
	flags.SetOutput(stderr)
	profile := flags.String("profile", "", "Go coverprofile path")
	var customThresholds thresholdFlags
	flags.Var(&customThresholds, "min", "package=percent threshold; repeatable; defaults to security-critical package baselines")
	if err := flags.Parse(args); err != nil {
		return 2
	}
	if strings.TrimSpace(*profile) == "" {
		fmt.Fprintln(stderr, "coverage-gate: --profile is required")
		return 2
	}

	file, err := os.Open(*profile)
	if err != nil {
		fmt.Fprintf(stderr, "coverage-gate: open profile: %v\n", err)
		return 1
	}
	defer file.Close()

	thresholds := []coveragegate.Threshold(customThresholds)
	if len(thresholds) == 0 {
		thresholds = coveragegate.DefaultThresholds()
	}
	results, evaluationErr := coveragegate.Evaluate(file, thresholds)
	for _, result := range results {
		status := "PASS"
		if result.Missing {
			status = "MISSING"
		} else if !result.Passed {
			status = "FAIL"
		}
		fmt.Fprintf(stdout, "%s %s %.1f%% >= %.1f%% (%d/%d statements)\n",
			status,
			result.Package,
			result.Percent,
			result.Minimum,
			result.Covered,
			result.Total,
		)
	}
	if evaluationErr != nil {
		fmt.Fprintf(stderr, "coverage-gate: %v\n", evaluationErr)
		return 1
	}
	return 0
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}
